POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@gmail.com",
  "password": "123456",
  "photos": "john_doe.png",
  "roles": [
    {
      "id": 3,
      "name": "Editor",
      "description": "Manage categories, brands, products, articles and menus"
    },
    {
      "id": 4,
      "name": "Shipper",
      "description": "Manage categories, brands, products, articles and menus"
    }
  ]
}

###
GET http://localhost:8080/api/v1/users/1

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Johnson",
  "email": "joe.johnson@gmail.com",
  "photos": "joe_johnson.png",
  "roles": [
    {
      "id": 1,
      "name": "Admin",
      "description": "Manage Everything"
    }
  ]
}

###
GET http://localhost:8080/api/v1/users

###
PUT http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "id": 1,
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@gmail.com",
  "password": "123456",
  "photos": "john_doe.png",
  "roles": [
    {
      "id": 4,
      "name": "Shipper",
      "description": "Manage categories, brands, products, articles and menus"
    },
    {
      "id": 5,
      "name": "Assistant",
      "description": "Manage questions and reviews"
    }
  ]
}

###
DELETE http://localhost:8080/api/v1/users/2


###
GET http://localhost:8080/api/v1/roles

